// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Construct connection URL for Turso if credentials exist
let dbUrl = process.env.DATABASE_URL;
if (process.env.TURSO_DATABASE_URL && process.env.TURSO_AUTH_TOKEN) {
  // Append authToken to URL if using libsql protocol
  // Note: Prisma CLI might need "libsql://...?authToken=..." format
  const baseUrl = process.env.TURSO_DATABASE_URL;
  if (baseUrl.startsWith("libsql://")) {
    dbUrl = `${baseUrl}?authToken=${process.env.TURSO_AUTH_TOKEN}`;
  } else {
    // Fallback for http/https URLs or other formats
    dbUrl = baseUrl;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  // Remove migrations config as we are using db push for now
  // migrations: {
  //   path: "prisma/migrations",
  // },
  datasource: {
    // Prisma config expects url string
    url: dbUrl,
  },
});
